/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html'],
  theme: {
    extend: {
      colors: {
        // Brand red palette — kept under the "blue" key to match the existing class names
        // that were generated by Antigravity. Don't rename — it would break dozens of classes.
        blue: {
          50:  '#fff0f0',
          100: '#ffcccc',
          200: '#ff9999',
          300: '#ff6666',
          400: '#ff3333',
          500: '#FF0000',
          600: '#cc0000',
          700: '#990000',
          800: '#660000',
          900: '#330000',
          950: '#1a0000',
        },
      },
    },
  },
  plugins: [
    function ({ addUtilities }) {
      const utilities = {};
      const rotateValues = [0, 5, 10, 15, 20, 30, 45, 75];
      const baseTransform = 'translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0)) rotateX(var(--tw-rotate-x, 0)) rotateY(var(--tw-rotate-y, 0)) rotateZ(var(--tw-rotate-z, 0)) skewX(var(--tw-skew-x, 0)) skewY(var(--tw-skew-y, 0)) scaleX(var(--tw-scale-x, 1)) scaleY(var(--tw-scale-y, 1))';

      rotateValues.forEach((v) => {
        utilities[`.rotate-x-${v}`] = { '--tw-rotate-x': `${v}deg`, transform: baseTransform };
        if (v !== 0) utilities[`.-rotate-x-${v}`] = { '--tw-rotate-x': `-${v}deg`, transform: baseTransform };
        utilities[`.rotate-y-${v}`] = { '--tw-rotate-y': `${v}deg`, transform: baseTransform };
        if (v !== 0) utilities[`.-rotate-y-${v}`] = { '--tw-rotate-y': `-${v}deg`, transform: baseTransform };
        utilities[`.rotate-z-${v}`] = { '--tw-rotate-z': `${v}deg`, transform: baseTransform };
        if (v !== 0) utilities[`.-rotate-z-${v}`] = { '--tw-rotate-z': `-${v}deg`, transform: baseTransform };
      });

      addUtilities({
        ...utilities,
        '.perspective-none': { perspective: 'none' },
        '.perspective-dramatic': { perspective: '100px' },
        '.perspective-near': { perspective: '300px' },
        '.perspective-normal': { perspective: '500px' },
        '.perspective-midrange': { perspective: '800px' },
        '.perspective-distant': { perspective: '1200px' },
        '.transform-style-preserve-3d': { 'transform-style': 'preserve-3d' },
        '.transform-style-flat': { 'transform-style': 'flat' },
      });
    },
  ],
};
